const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
let state=null;let decisionStarted=Date.now();let busy=false;
const statLabels={academic:"学业",health:"健康",social:"社交",empathy:"共情",openness:"开放",stress:"压力",mood:"心情",energy:"精力"};
async function api(url,options={}){const response=await fetch(url,{headers:{"Content-Type":"application/json"},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||"请求失败");return data}
function loading(show,text="正在处理……"){busy=show;$("#loadingText").textContent=text;$("#loading").classList.toggle("hidden",!show)}
async function startSession(event){event.preventDefault();if(busy)return;const payload={name:$("#nameInput").value.trim()};const seed=$("#seedInput").value.trim();if(seed)payload.seed=Number(seed);try{loading(true,"Designer 正在决定本局的时间密度与回合数……");state=await api("/api/session",{method:"POST",body:JSON.stringify(payload)});localStorage.setItem("boy-session",state.session_id);$("#landing").classList.add("hidden");$("#game").classList.remove("hidden");enableTools();render()}catch(error){toast(error.message,true)}finally{loading(false)}}
async function submitAction(action,freeText=""){if(!state||state.finished||busy)return;try{loading(true,"Controller 正在记录行为并续写这一刻……");state=await api(`/api/session/${state.session_id}/act`,{method:"POST",body:JSON.stringify({action,free_text:freeText,hesitation_ms:Date.now()-decisionStarted})});$("#freeText").value="";updateCount();render();toast(state.last_result.advanced?"本回合结束，时间线向前推进":"行为、耗时与状态变化已记录")}catch(error){toast(error.message,true)}finally{loading(false)}}
function render(){const {profile,scene,design}=state;const total=design.turn_policy.total_turns;$("#playerName").textContent=profile.name;$("#avatar").textContent=profile.name[0];$("#profileMeta").textContent=`${profile.class_name} · ${profile.traits.join(" / ")}`;$("#providerLabel").textContent=design.generator==="llm"?"LLM DESIGNER":"LOCAL DESIGNER";$("#dateLabel").textContent=`${scene.month} · ${scene.period}`;$("#sceneTitle").textContent=scene.title;$("#toneLabel").textContent=scene.tone||"日常";$("#turnLabel").textContent=state.finished?"五个月体验完成":`第 ${state.turn+1} / ${total} 回合`;$("#progressBar").style.width=`${state.finished?100:scene.progress}%`;$("#apLabel").textContent=state.ap;$("#dynamicTurns").textContent=total;$("#sceneIntro").textContent=state.finished?"寒假仍在继续，而这段被记录的校园生活暂时停在这里。现在可以查看完整研究报告与行为轨迹。":scene.intro;renderChoices();renderResult();renderStatus();renderLab();decisionStarted=Date.now()}
function renderChoices(){const grid=$("#choiceGrid");if(state.finished){grid.innerHTML='<button class="choice" id="finalReport" type="button"><span>REPORT</span><b>查看完整研究报告</b><p>汇总行为证据、决策耗时与文本质量。</p><small>打开报告 →</small></button>';$("#finalReport").onclick=showReport}else{grid.innerHTML=state.options.map((option,index)=>`<button class="choice" data-action="${option.id}" type="button"><span>0${index+1}</span><b>${option.label}</b><p>${option.description}</p><small>${option.effects_text}</small></button>`).join("");$$('[data-action]').forEach((button)=>button.onclick=()=>submitAction(button.dataset.action))}$("#freeAction").classList.toggle("hidden",state.finished)}
function renderResult(){const box=$("#lastResult");if(!state.last_result){box.classList.add("hidden");return}box.classList.remove("hidden");box.innerHTML=`<p>${state.last_result.narrative}</p><div class="change-list">${state.last_result.changes.map((change)=>`<span>${change.label} ${change.delta>0?"+":""}${change.delta} → ${change.value}</span>`).join("")}</div>`}
function renderStatus(){$("#stats").innerHTML=Object.entries(state.stats).map(([key,value])=>`<div class="stat-row ${key==="stress"?"is-stress":""}"><div><span>${statLabels[key]}</span><b>${value}</b></div><div class="stat-track"><i style="width:${value}%"></i></div></div>`).join("");$("#npcList").innerHTML=state.npcs.map((npc)=>{const relation=state.relationships[npc.id];return `<article class="person-row" title="${npc.note}"><span class="person-avatar">${npc.name[0]}</span><div><b>${npc.name}</b><small>${npc.role} · ${relation.impression}</small></div><strong>${relation.friendship}</strong></article>`}).join("")}
function renderLab(){const critic=state.critic_preview;$("#completion").textContent=`${critic.completion}%`;$("#ring").style.background=`conic-gradient(var(--mint) ${critic.completion*3.6}deg,#e5e9e2 0)`;$("#criticSummary").textContent=critic.summary;$("#dimensions").innerHTML=Object.entries(critic.dimensions).slice(0,6).map(([name,value])=>`<div class="dimension-row"><div><span>${name}</span><b>${value}</b></div><div><i style="width:${value}%"></i></div></div>`).join("");const design=state.design;$("#designInfo").innerHTML=keyValues([["generator",design.generator],["title",design.title],["dynamic turns",design.turn_policy.total_turns],["AP / turn",design.turn_policy.action_points_per_turn],["pace",design.style.pace],["NPC count",design.npcs.length],["rationale",design.turn_policy.rationale],["session",state.session_id],["seed",state.seed]]);$("#eventCount").textContent=`${state.history.length} 条行为`;$("#traceList").innerHTML=state.history.length?[...state.history].reverse().map((row)=>`<article class="trace-item"><div><span>TURN ${row.turn+1}</span><time>${formatTime(row.hesitation_ms)}</time></div><h4>${row.action_label}</h4>${row.free_text?`<p>“${escapeHtml(row.free_text)}”</p>`:""}<small>${Object.entries(row.effects).map(([key,value])=>`${statLabels[key]} ${value>0?"+":""}${value}`).join(" · ")}</small></article>`).join(""):'<p class="empty">尚未产生行为记录。</p>'}
function keyValues(rows){return rows.map(([key,value])=>`<div><span>${key}</span><b>${value}</b></div>`).join("")}
async function showReport(){if(!state)return toast("请先创建一局游戏",true);try{const report=await api(`/api/session/${state.session_id}/report`);$("#reportContent").innerHTML=`<div class="report-summary"><span>${report.sample_size} 条证据</span><span>${report.average_hesitation_ms} ms 平均耗时</span><span>${report.completion}% 完成度</span></div><p class="report-lead">${report.summary}</p><div class="report-grid">${Object.entries(report.dimensions).map(([name,value])=>`<div><span>${name}</span><b>${value}</b><i><em style="width:${value}%"></em></i></div>`).join("")}</div><div class="report-note"><b>研究边界</b><p>${report.research_note||report.disclaimer}</p></div>`;$("#reportDialog").showModal()}catch(error){toast(error.message,true)}}
function openDrawer(drawer){closeDrawers();drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");$("#scrim").classList.remove("hidden");drawer.querySelector("button").focus()}
function closeDrawers(){$$(".drawer").forEach((drawer)=>{drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true")});$("#scrim").classList.add("hidden")}
function enableTools(){$("#statusBtn").disabled=false;$("#labBtn").disabled=false}
function exportSession(){if(!state)return;const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`because-of-you-${state.session_id}.json`;link.click();URL.revokeObjectURL(link.href);toast("本局数据已导出")}
function formatTime(ms){return ms<1000?`${ms} ms`:`${(ms/1000).toFixed(1)} s`}
function escapeHtml(text){const node=document.createElement("div");node.textContent=text;return node.innerHTML}
function updateCount(){$("#charCount").textContent=$("#freeText").value.length}
function toast(message,error=false){const box=$("#toast");box.textContent=message;box.classList.toggle("error",error);box.classList.add("show");setTimeout(()=>box.classList.remove("show"),2200)}
$("#launchForm").addEventListener("submit",startSession);$("#freeBtn").onclick=()=>{const text=$("#freeText").value.trim();text?submitAction("free",text):toast("请先写下一件具体行动",true)};$("#freeText").addEventListener("input",updateCount);$("#freeText").addEventListener("keydown",(event)=>{if((event.ctrlKey||event.metaKey)&&event.key==="Enter")$("#freeBtn").click()});$("#playerChip").onclick=()=>openDrawer($("#statusDrawer"));$("#statusBtn").onclick=()=>openDrawer($("#statusDrawer"));$("#labBtn").onclick=()=>openDrawer($("#labDrawer"));$("#hintChip").onclick=()=>openDrawer($("#labDrawer"));$("#scrim").onclick=closeDrawers;$$('[data-close]').forEach((button)=>button.onclick=closeDrawers);$("#reportBtn").onclick=showReport;$("#closeReport").onclick=()=>$("#reportDialog").close();$("#exportBtn").onclick=exportSession;$("#newBtn").onclick=()=>{if(!state||confirm("确定重新开始吗？当前数据可先从研究台导出。")){localStorage.removeItem("boy-session");location.reload()}};$$('[data-tab]').forEach((button)=>button.onclick=()=>{$$('[data-tab]').forEach((item)=>item.classList.toggle("active",item===button));["critic","designer","trace"].forEach((name)=>$("#"+name+"Tab").classList.toggle("hidden",name!==button.dataset.tab))});document.addEventListener("keydown",(event)=>{if(event.key==="Escape")closeDrawers()});
(async function restore(){const id=localStorage.getItem("boy-session");if(!id)return;try{loading(true,"正在恢复上一次校园记录……");state=await api(`/api/session/${id}`);$("#landing").classList.add("hidden");$("#game").classList.remove("hidden");enableTools();render()}catch{localStorage.removeItem("boy-session")}finally{loading(false)}})();

